//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DeployTask
    {
        public string TaskID { get; set; }
        public string ProejctID { get; set; }
        public string ProejctCode { get; set; }
        public string ProjectName { get; set; }
        public string PackageID { get; set; }
        public string PackageVersion { get; set; }
        public string PackageName { get; set; }
        public string ServerID { get; set; }
        public int ServerIndex { get; set; }
        public int DeploymentType { get; set; }
        public string DeploymentPath { get; set; }
        public string FtpLoginUser { get; set; }
        public string FtpLoginPwd { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> DeployTime { get; set; }
    }
}
