//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ProjectCodeServer
    {
        public string ServerID { get; set; }
        public int ServerIndex { get; set; }
        public int DeploymentType { get; set; }
        public string ProjectID { get; set; }
        public string Path { get; set; }
        public string FtpLoginUser { get; set; }
        public string FtpLoginPwd { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
