//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ProjectPackage
    {
        public string PackageID { get; set; }
        public string ProjectID { get; set; }
        public string Version { get; set; }
        public string PackageName { get; set; }
        public string PackagePath { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
