//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STEntities : DbContext
    {
        public STEntities()
            : base("name=STEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<D_Project> D_Project { get; set; }
        public DbSet<D_ProjectCodeServer> D_ProjectCodeServer { get; set; }
        public DbSet<D_ProjectPackage> D_ProjectPackage { get; set; }
        public DbSet<D_SqlServer> D_SqlServer { get; set; }
    }
}
